name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Fortran compiler
      run: sudo apt-get update && sudo apt-get install -y gfortran

    - name: Build Fortran library
      run: cmake -B build && cmake --build build
    
    - name: tree
      run: tree

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

   
    - name: Install packaging tools
      run: pip install --upgrade build

    - name: Build wheel
      run: python -m build --wheel

    - name: List built artifacts
      run: ls -l dist

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: msise00-wheel
        path: dist/*.whl

  macos:
    needs: linux
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system build tools
        run: |
          brew update
          brew install cmake gcc make

      - name: Build Fortran driver
        run: |
          cmake -B build
          cmake --build build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install packaging tools
        run: pip install --upgrade build

      - name: Build wheel
        run: python -m build --wheel

      - name: List built artifacts
        run: ls -l dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: msise00-wheel-macos
          path: dist/*.whl

      - name: Test wheel install
        run: |
          pip install dist/*.whl[tests]
          pytest
        env:
          FC: gfortran-11

  windows:
    needs: linux
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system build tools
        shell: bash
        run: |
          # install MinGW / gfortran and CMake
          choco install mingw cmake make --yes
          refreshenv

      - name: Build Fortran driver
        shell: bash
        run: |
          cmake -B build -G "MinGW Makefiles"
          cmake --build build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install packaging tools
        run: pip install --upgrade build

      - name: Build wheel
        run: python -m build --wheel

      - name: List built artifacts
        run: dir dist

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: msise00-wheel-windows
          path: dist/*.whl

      - name: Test wheel install
        run: |
          pip install dist\*.whl[tests]
          pytest