name: ci

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (for cibuildwheel)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Install system dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y cmake gfortran make
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install cmake gcc make
          fi

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install mingw cmake make --yes
          $env:PATH += ";C:\ProgramData\chocolatey\bin"

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp3{9,10,11,12}-*"
          CIBW_ENVIRONMENT: >
            CMAKE_BUILD_TYPE=Release
            CMAKE_BUILD_PARALLEL_LEVEL=3
        run: cibuildwheel --output-dir wheelhouse

      - name: List built wheels
        run: ls -l wheelhouse

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*.whl